### PR TITLE
Add php 8.3 to build jobs

### PR DESCRIPTION
**Pull request by 84m**
Adding php8.3 to the current build jobs

### CODE REVIEW

**Comment by 84m** [comment]
Hey @HeahDude,
i would love approval here, to get the workflow running ;-)

**Comment by HeahDude** [comment]
@84m thanks for the PR!
It seems we need to fix a bit more the workflow run on low deps, do you want to give it a try or do you want me to handle it by pushing on your branch (probably tomorrow)?

**Comment by 84m** [comment]
> [...] do you want to give it a try or do you want me to handle it by pushing on your branch (probably tomorrow)?

sure, go ahead. I justed fixed the codestyle as a quick fix, but would also need to dig deeper on why the lowest-ci is currently failing.

**Comment by HeahDude** [comment]
Thank you @84m

**Pull request merged**
