### PR TITLE
[3.0] Fixed warming up custom configs and added support for custom config definition

### PR DESCRIPTION
**Pull request by HeahDude**
Definitely fixes https://github.com/Exercise/HTMLPurifierBundle/issues/22, while closing https://github.com/Exercise/HTMLPurifierBundle/issues/26 and https://github.com/Exercise/HTMLPurifierBundle/issues/34.

 - [BC break] Dropped support for PHP 5.x. PHP 7.1 minimum required.
 - Added a new HTMLPurifierConfigFactory to handle cache properly and to
   build custom html definition from bundle configuration.
 - [BC Break] The bundle configuration has changed
 - Added CHANGELOG and UPGRADE files
 - Refactored `SerializerCacheWarmer` to preload each profile configuration
 - [BC break] Added type hints and return type hints

TODO:
 - [x] Update Flex recipe

### CODE REVIEW

**Comment by HeahDude** [comment]
ping @XWB @stof

**Comment by stof** [comment]
As 2.0 has already been tagged, a BC break on the configuration is not really possible anymore.

**Comment by spolischook** [comment]
@stof should we keep this until version 3.0?

**Comment by XWB** [comment]
@HeahDude Another solution would be adding the new configuration, and deprecating the old one.

**Comment by stof** [comment]
@XWB the hard part with that is that the existing config has prototyped node for profiles as the root node itself, making it hard to introduce anything else new.

Btw, that's one of the reason why having a prototyped node as the root is a bad idea (the other reason is that it makes it impossible to support XML config files)

**Comment by HeahDude** [comment]
@XWB, not sure it is worth it, we should think about a 3.0 release instead, if we really want this new config, what I would vote to. I don't think we should add complexity here because we made a tag too soon.

We did such thing in the FrameworkExtraBundle, the 4.0 has never really had the time to be required somewhere. Here some months have passed, but I don't think it's an issue actually.

**Comment by jon-ht** [comment]
Hey,

I'd like to use your PR but I'm facing a problem with cache warmup. It gives me this error

`User Warning: Base directory (...)\var\cache\dev/htmlpurifier does not exist,
please create or change using %Cache.SerializerPath`

image

My config is really simple

```yml
exercise_html_purifier:
    html_profiles:
        # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html
#        default:
#            config:
#                Cache.SerializerPermissions: 777
        notice:
            config:
                HTML.Allowed: 'strong,p[class]'
            elements:
                hide:
                    - Inline
                    - Inline
                    - Common
```

This error is thrown by [this line](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/DefinitionCache/Serializer.php#L232-L236) in [ezyang/htmlpurifier](https://github.com/ezyang/htmlpurifier)

It should be a simple warning but Symfony CacheWarmer breaks and fails to build the rest of cache files. I'm not having any trouble if I use master branch

**Comment by bobvandevijver** [comment]
@HeahDude Is there any progress on this feature? I would really like to use this, instead of overwriting the config factory myself.

**Comment by bastos71** [comment]
@stof will this PR be merged soon ? More and more we are facing problems regarding rights problems in cache directory, creating issues during deployments and during dev steps ...

**Comment by stof** [comment]
@bastos71 no idea. I'm not the maintainer.

**Comment by bastos71** [comment]
oh sorry, then @spolischook ? or @HeahDude ?

**Comment by spolischook** [comment]
@HeahDude could you please resolve conflicts

**Comment by HeahDude** [comment]
The PR has BC breaks, we need a v3 now that v2 has been tagged. I'll try to update the PR this week end.

**Comment by HeahDude** [comment]
Ready for review again (ping @stof), I've fixed @jon-ht bug report. @jon-ht could you confirm please?

**Comment by jon-ht** [comment]
@HeahDude I'm sorry but I'm not on the project using this bundle anymore. But I guess applying my config above might give you an idea on the resolution

**Comment by HeahDude** [comment]
Test are green 🎉, I try to get a better tests coverage then I merge.

**Pull request merged**
