### PR TITLE
Support PHP 8.0

### PR DESCRIPTION
**Pull request by pierres**

### CODE REVIEW

**Comment by HeahDude** [comment]
Hello @pierres, many thanks for that PR! And happy holidays to you!

Could you please try to declare "XDEBUG_MODE=coverage" using the `phpunit.xml.dist`?
The CI is currently failing on the coverage step: https://travis-ci.org/github/Exercise/HTMLPurifierBundle/builds/751811763.

**Comment by HeahDude** [comment]
Just noticed that the Xdebug issue is not caused by your changes, sorry. Thanks for working on it though.

**Comment by pierres** [comment]
Yes, the Xdebug issue was unrelated and caused by the Xdebug 3 update. I rebased the PR to have two separate commits.

**Comment by HeahDude** [comment]
Thank you @pierres for this nice contribution, 3.1 is now tagged :).

Happy holidays!

**Pull request merged**
