### PR TITLE
#76: Allow null input in Twig extension

### PR DESCRIPTION
**Pull request by bobvandevijver**
See #76, this should allow for null input and return an empty string if so.

### CODE REVIEW

**Comment by HeahDude** [comment]
Thank you! Could you please fix the cs to make the CI green?

**Comment by bobvandevijver** [comment]
That should do it! Can you squash it when merging?

**Comment by HeahDude** [comment]
Yes thanks! I'll do this evening

**Comment by HeahDude** [comment]
Thank you!

**Pull request merged**
